services:
  db_postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - smart_route
    volumes:
      - postgres_database:/var/lib/postgresql/data

networks:
  smart_route:

volumes:
  postgres_database: